"""empty message

Revision ID: c06463b9bcbc
Revises: 
Create Date: 2021-03-26 09:12:20.706607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06463b9bcbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('givenname', sa.String(length=40), nullable=True),
    sa.Column('surname', sa.String(length=40), nullable=True),
    sa.Column('jhed_id', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_administrator', sa.Boolean(name='is_administrator'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('length', sa.Interval(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.String(length=40), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_campaigns_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=40), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_projects_added_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('campaign_id', sa.String(length=40), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_candidates_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_candidates_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_table('nominations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('nomination_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_nominations_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nominations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nominations'))
    )
    op.create_table('votes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('campaign_id', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('votes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_votes_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_votes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('nominations')
    op.drop_table('candidates')
    op.drop_table('projects')
    op.drop_table('campaigns')
    op.drop_table('users')
    # ### end Alembic commands ###
