---
name: Jira Integration
on:
  issues:
    types: [ opened, closed ]

jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: create ticket
        id: create
        uses: atlassian/gajira-create@master
        if: github.event.issue.state == 'open'
        with:
          project: OPS
          issuetype: Task
          summary: |
            [ ${{ github.repository }} - ${{ github.event.issue.number }} ] ${{ github.event.issue.title }}
          description: |
            ${{ github.event.issue.body }}

      - name: Find Key in Title
        if: github.event.issue.state != 'open'
        id: find
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.event.issue.number }}
        
      - name: transition to resolved
        if: github.event.issue.state == 'closed'
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.find }}
          transition: "closed"
