---
name: Jira Integration
on:
  issues:
    types: [ opened, closed ]

jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: Context dump
        env:
          GITHUB_CONTEXT: toJson(github)
        run: |
          echo $GITHUB_CONTEXT
          
      - name: login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: create ticket
        id: create
        uses: atlassian/gajira-create@master
        if: github.event.issue.state == 'open'
        with:
          project: OPS
          issuetype: Task
          summary: |
            [ ${{ github.repository }} - ${{ github.event.issue.number }} ] ${{ github.event.issue.title }}
          description: |
            ${{ github.event.issue.body }}

      - name: link github issue to jira issue
        id: link
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Linked to Jira: ${{ steps.create.outputs.issue }} '
            })

      - name: update original github issue to include key in title
        id: linktitle
        uses: actions/github-script@v4
        env:
          ISSUE_OWNER: github.event.issue.owner
          ISSUE_REPO: github.event.issue.repository
          ISSUE_NUMBER: github.event.issue.number
          ISSUE_TITLE: github.event.issue.title
        with:
          script: |
            github.issues.update({
              owner: ${ISSUE_OWNER},
              repo: ${ISSUE_REPOSITORY},
              issue_number: ${ISSUE_NUMBER},
              title: [ ${{ steps.create.outputs.issue }}] ${ISSUE_TITLE}
              })
            
      - name: Find Key in Title
        if: github.event.issue.state != 'open'
        id: find
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: github.event.issue.title
        
      - name: transition to resolved
        if: github.event.issue.state == 'closed'
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.find }}
          transition: "closed"
